version: '3'

services:
  backend:
    container_name: backend
    build: 
      context: backend
      dockerfile: Dockerfile
    image: backend
    restart: unless-stopped
    env_file: .env
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    networks:
      - backend
      - frontend

  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    env_file: .env
    restart: unless-stopped
    ports:
      - '8081:80'
    networks:
      - frontend
      
  postgres:
    container_name: db
    image: postgres:latest
    env_file: .env
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped
    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend:
  frontend: